export const ADD = 'todos/ADD'
export const DELETE = 'todos/DELETE'
export const EDIT = 'todos/EDIT'
export const COMPLETE = 'todos/COMPLETE'
export const TOGGLE_ALL = 'todos/TOGGLE_ALL'
export const CLEAR_COMPLETED = 'todos/CLEAR_COMPLETED'
